version: 2

builds:
  - id: foxess-prometheus-exporter
    binary: foxess-prometheus-exporter
    goos:
      - linux
    goarch:
      - amd64
      - arm64

kos:
  - build: foxess-prometheus-exporter
    repositories:
      - ghcr.io/{{ .Owner }}/{{ .Name }}
    tags:
      - "{{ .Tag }}"
      - latest

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .Env.GITHUB_REPOSITORY_NAME }}"
