version: 2

builds:
  - id: foxess-exporter
    binary: foxess-exporter
    goos:
      - linux
    goarch:
      - amd64
      - arm64

kos:
  - repository: ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .Env.GITHUB_REPOSITORY_NAME }}
    build: foxess-exporter
    tags:
      - "{{ .Tag }}"
      - latest

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .Env.GITHUB_REPOSITORY_NAME }}"
