version: 2

builds:
  - id: foxess-exporter
    binary: foxess-exporter
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers:
  - image_templates:
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:{{ .Tag }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY }}:latest"
    dockerfile: Dockerfile

release:
  github:
    owner: "{{ .Env.GITHUB_REPOSITORY_OWNER }}"
    name: "{{ .Env.GITHUB_REPOSITORY_NAME }}"
